---
- name: File copy modules
  hosts: all
  tasks:
    - name: Copy file demo
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /tmp/
        mode: "0644"

    - name: Add some lines to /tmp/hosts
      ansible.builtin.blockinfile:
        path: /tmp/hosts
        block: |
          0.0.0.0 host1.example.com
        state: present

    - name: Verify file checksum
      ansible.builtin.stat:
        path: /tmp/hosts
        checksum_algorithm: md5
      register: result

    - name: Display file checksum
      ansible.builtin.debug:
        msg: "The checksum of /tmp/hosts is {{ result.stat.checksum }}"

    - name: Fetch a file
      ansible.builtin.fetch:
        src: /tmp/hosts
        dest: /tmp/
