---
- name: Install and run vsftpd
  gather_facts: false
  hosts: all
  tasks:
    - name: Install the package
      package:
        name: vsftpd
    - name: Run the service
      service:
        name: vsftpd
        state: started
        enabled: true
    - name: Open firewall
      firewalld:
        service: ftp
        state: enabled
        permanent: true
        immediate: true
