---
- name: Install and run vsftpd
  gather_facts: false
  hosts: all
  tasks:
    - name: Install the package
      ansible.builtin.package:
        name: vsftpd
    - name: Run the service
      ansible.builtin.service:
        name: vsftpd
        state: started
        enabled: true
    - name: Open firewall
      ansible.posix.firewalld:
        service: ftp
        state: enabled
        permanent: true
        immediate: true
