---
- name: install start and enable httpd
  gather_facts: false
  hosts: all
  tasks:
    - name: install package
      package:
        name: httpd
        state: latest
    - name: start and enable service
      service:
        name: httpd
        state: started
        enabled: true
    - name: open port in firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

- name: test httpd accessibility
  become: false
  hosts: localhost
  tasks:
    - name: test httpd access
      uri:
        url: http://vm-alma
