---
- name: install and run vsftpd
  gather_facts: false
  hosts: all
  tasks:
    - name: install the package
      package:
        name: vsftpd
    - name: run the service
      service:
        name: vsftpd
        state: started
        enabled: true
    - name: open firewall
      firewalld:
        service: ftp
        state: enabled
        permanent: true
        immediate: true
