---
- name: Install start and enable httpd
  gather_facts: false
  hosts: all
  tasks:
    - name: Install package
      package:
        name: httpd
        state: latest
    - name: Start and enable service
      service:
        name: httpd
        state: started
        enabled: true
    - name: Open port in firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

- name: Test httpd accessibility
  become: false
  hosts: localhost
  tasks:
    - name: Test httpd access
      uri:
        url: http://vm-alma
