---
- name: Create a user using variables
  hosts: all
  vars:
    user: thomas
  tasks:
    - name: Create a user {{ user }} on host {{ ansible_hostname }}
      ansible.builtin.user:
        name: "{{ user }}"
